; ESP32-S3-WROOM-1-N16R8 (16MB QIO Flash + 8MB OPI PSRAM)
; Target board: Retro-Pixel (HD231005C10 / ILI9342, see retro-pixel-datasheet.md)

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf
monitor_speed = 115200
build_flags =
    -DMIA_ESPIDF_APP_MAIN
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOG_TO_USB_CDC=1
lib_deps =
    adafruit/Adafruit GFX Library
    xreef/SimpleFTPServer
